-- =====================================================================
-- KinoXP - Seed Data
-- =====================================================================

-- Insert theaters
INSERT INTO theaters (theater_name, total_rows, seats_per_row) VALUES
('Sal 1', 20, 12),
('Sal 2', 25, 16)
ON DUPLICATE KEY UPDATE
    theater_name = VALUES(theater_name),
    total_rows = VALUES(total_rows),
    seats_per_row = VALUES(seats_per_row);

-- Generate seats for Sal 1 (20 rows x 12 seats = 240 seats)
INSERT IGNORE INTO seats (theater_id, `row_number`, seat_number)
SELECT 1, r, s
FROM (
    SELECT 1 AS r UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
) AS row_nums
CROSS JOIN (
    SELECT 1 AS s UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12
) AS seat_nums;

-- Generate seats for Sal 2 (25 rows x 16 seats = 400 seats)
INSERT IGNORE INTO seats (theater_id, `row_number`, seat_number)
SELECT 2, r, s
FROM (
    SELECT 1 AS r UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20 UNION
    SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
) AS row_nums
CROSS JOIN (
    SELECT 1 AS s UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION
    SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10 UNION
    SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION
    SELECT 16
) AS seat_nums;
