name: Publish

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "pom.xml"
      - "Dockerfile"
      - ".github/workflows/publish.yaml"

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00  # v4.7.1
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run tests
        run: mvn -B -q test

      - name: Build JAR
        run: mvn -B -q package -DskipTests

      - name: Log in to GHCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/kino
          COMMIT=${{ github.sha }}
          docker build -t $IMAGE:latest -t $IMAGE:$COMMIT .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/kino
          COMMIT=${{ github.sha }}
          docker push $IMAGE:latest
          docker push $IMAGE:$COMMIT
